# Generated by Django 5.2.8 on 2025-11-14 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_name', models.CharField(max_length=500)),
                ('event_url', models.URLField(max_length=1000)),
                ('event_image', models.URLField(max_length=1000)),
                ('event_datetime', models.DateTimeField()),
                ('venue_name', models.CharField(max_length=500)),
                ('venue_address', models.CharField(blank=True, max_length=500, null=True)),
                ('venue_city', models.CharField(max_length=200)),
                ('venue_state', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'event_id')},
            },
        ),
    ]
