# Generated by Django 5.2.8 on 2025-11-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='price_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
