# Generated by Django 5.2.8 on 2025-12-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_favoriteevent_last_updated_favoriteevent_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_datetime',
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='event_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='event_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
