# Generated by Django 5.2.8 on 2025-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_favoriteevent_event_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
